#########################################################################################################
# Handles CI checks for pull requests and pushed to all key branches
#########################################################################################################
name: CI Checks

concurrency:
  group: '${{ github.workflow }} - ${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

on:
  push:
    branches:
      - master
      - alpha
      - next
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.x'
      - '[0-9]+.x'
  pull_request:
    branches:
      - master
      - alpha
      - next
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.x'
      - '[0-9]+.x'

jobs:
  call-checks-workflow:
    name: "Check workflow"
    uses: elastic/elastic-charts/.github/workflows/shared/checks.yml@next
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Print context
        shell: python
        run: |
          print("""${{ toJSON(github) }}""")
