on:
  repository_dispatch:
    types: [test_result_old]

jobs:
  test-why:
    name: WHYYYY
    runs-on: ubuntu-latest
    # environment:
    #   name: nick
    #   url: https://example.com/
    steps:
      - name: Print github context
        shell: python
        run: |
          print("""${{ toJSON(github.event) }}""")
